version: '3.8'
services:
  app:
    image: php:7.4-fpm
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  composer:
    image: composer:latest
    container_name: composer-container
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ["composer"]

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
